server:
  port: ${SERVER_PORT:8080} # Gateway port

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: hotel-service
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**

        - id: rating-service
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

